insert into persons (name, email) values
('Michel Vivian', 'MichelVivian@gmail.com'),
('Rosangela Olbermann', 'RosangelaOlbermann@gmail.com'),
('Cristiane Flach', 'CristianeFlach@gmail.com'),
('Gilnei Vogel', 'GilneiVogel@gmail.com'),
('Graciane Hammes', 'GracianeHammes@gmail.com'),
('Ederson Lauschener', 'ederson.lauschener@example.com'),
('Tainara Paula Klein', 'tainara.paula.klein@example.com'),
('Paulo Miguel Telocken', 'paulo.miguel.telocken@example.com'),
('Lucas Josias Rohr', 'lucas.josias.rohr@example.com'),
('Carol Cristina dos Santos', 'carol.cristina.santos@example.com'),
('Schirley Suzane Stahl Leonhard', 'schirley.suzane.leonhard@example.com'),
('Bárbara Eichelberger Klein', 'barbara.eichelberger.klein@example.com'),
('Luize Gracieli Giacomolli de Oliveira', 'luize.giacomolli.oliveira@example.com'),
('Roberto Bonelli Bittencourt Filho', 'roberto.bonelli.bittencourt@example.com'),
('Priscila Elis Signor', 'priscila.elis.signor@example.com'),
('Kauana Vailon', 'kauana.vailon@example.com'),
('Clédina de Oliveira S. dos Santos', 'cledina.oliveira.santos@example.com'),
('Lauana Boing', 'lauana.boing@example.com'),
('Daniel Gaspareto', 'daniel.gaspareto@example.com'),
('Anelize Gregory', 'anelize.gregory@example.com'),
('Ivan Carvalho da Rosa', 'ivan.carvalho.rosa@example.com'),
('Mariana Vedovatto', 'mariana.vedovatto@example.com'),
('José Ronaldo Marques', 'jose.ronaldo.marques@example.com'),
('Fátima de Matos Marques', 'fatima.matos.marques@example.com'),
('Zenaide Schmitz', 'zenaide.schmitz@example.com'),
('Silmara T. Freitas', 'silmara.freitas@example.com'),
('Adriana Meneghetti', 'adriana.meneghetti@example.com'),
('Douglas Tadeu Silva', 'douglas.tadeu.silva@example.com'),
('Keity Andrieli Santoro', 'keity.andrieli.santoro@example.com'),
('Mateus Schabarum', 'mateus.schabarum@example.com'),
('Raquel Bulegon', 'raquel.bulegon@example.com'),
('Rejane Cerizzolli', 'rejane.cerizzolli@example.com'),
('Simone S. Juwer', 'simone.juwer@example.com'),
('Stela Niero', 'stela.niero@example.com'),
('Marcia Meneghetti Dalvesco', 'marcia.dalvesco@example.com'),
('Renata Laranjeira', 'renata.laranjeira@example.com'),
('Rafael Variani', 'rafael.variani@example.com'),
('Angelita Schmitt', 'angelita.schmitt@example.com'),
('Renan Borgheti', 'renan.borgheti@example.com'),
('Jorge Trento', 'jorge.trento@example.com'),
('Ricardo Hendges', 'ricardo.hendges@example.com'),
('Kátia Beltrame', 'katia.beltrame@example.com'),
('Juliano Rambo', 'juliano.rambo@example.com'),
('Francieli Pavalecini', 'francieli.pavalecini@example.com'),
('Gabriela Peretti', 'gabriela.peretti@example.com'),
('Mateus Batistella', 'mateus.batistella@example.com'),
('Juliano Eichelberger', 'juliano.eichelberger@example.com'),
('Ilvacir Franceschi', 'ilvacir.franceschi@example.com'),
('Maria Júlia Vellozo', 'maria.julia.vellozo@example.com');
